### ISSUE TITLE
Inventory rest api

### ISSUE THREAD

**Issue by diokey** [OpenHMIS/openmrs-module-openhmis.inventory#188]
Hi there,

Thank you for creating this module, I find it really useful. I was looking into ways to use this to integrate with another external application. 
I see the resources definition in the webservices.rest module, but when I test it I get errors. 

For example, I tried
```sh
curl -X GET --header 'Accept: application/json' 'https://openmrs.vecnacares.org/openmrs/ws/rest/v1/inventory/item'
```
This is the response I get

```json
{
  "error": {
    "message": "Resource does not exist. Please check documentation for implemented resources and their paths [Unknown resource: v1/inventory]",
    "code": "org.openmrs.module.webservices.rest.web.api.impl.RestServiceImpl:419",
    "detail": "org.openmrs.module.webservices.rest.web.response.UnknownResourceException:..."
  }
}
```
Is there any plan to exposes resources via a Restful api? 

Thank you!

**Comment by andrewmoko** [comment]
The inventory module exposes its Resources via REST. 

Try https://openmrs.vecnacares.org/openmrs/ws/rest/v2/inventory/item

**Comment by diokey** [comment]
Ooh, got it! Thank you!
